spring:
  application:
    name: eureka-client-facebook
  devtools:
        restart:
          enabled: true
        livereload:
             enabled: true  
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    
endpoints:
  actuator:
    enabled: true
  info:
    sensitive: false
    
banner:
  location: classpath:/config/banner.txt