server:
    port: 8088
    session:
      cookie:
        name: FBUISESSION
    auth-logout-uri: http://localhost:8087/auth/logout
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8087/auth/oauth/token
      userAuthorizationUri: http://localhost:8087/auth/oauth/authorize
      
    resource:
      userInfoUri: http://localhost:8087/auth/api/principal
      

spring:
  devtools:
    restart:
      enabled: true    
    livereload:
      enabled: true    
  thymeleaf:
     cache: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %c{1}:%L - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %c{1}:%L - %msg%n"
  level:
    root: INFO
    com.kaveinga.facebook: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  path: logs
  