version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8098:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:test@host.docker.internal:5555/springboot_with_hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: test
      
  springboot-with-hasura:
    image: 'springboot-with-hasura:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-with-hasura
    ports:
    - "8899:8899"
    restart: always
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5555/springboot_with_hasura?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      spring.datasource.username: postgres
      spring.datasource.password: test
volumes:
  db_data:

